[build]
builder = "railpack"
buildCommand = "go build -ldflags=\"-w -s\" -o out ./cmd/server"

[deploy]
startCommand = "./out"
healthcheckPath = "/healthz"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
